- hosts: dev
  tasks: 
       - name: apache tomcat install
         apt: name=tomcat8 update_cache=yes
         become: yes
       - name: enable tomcat startup
         systemd: name=tomcat8 enabled=yes state=restarted
         become: yes
